export const codeLangKeys = [
  "auto",
  "html",
  "javascript",
  "typescript",
  "python",
  "java",
  "c",
  "cpp",
  "csharp",
  "php",
  "css",
  "scss",
  "less",
  "markdown",
  "json",
  "yaml",
  "xml",
  "bash",
  "sql",
  "go",
  "rust",
  "dart",
  "kotlin",
  "swift",
  "ruby",
  "objective-c",
  "perl",
  "powershell",
  "r",
  "scala",
  "shellscript",
  "vb",
  "lua",
  "fsharp",
  "groovy",
  "ini",
  "latex",
  "matlab",
  "pascal",
  "plaintext",
  "pug",
  "restructuredtext",
  "vhdl",
  "vue",
  "coffeescript",
  "dockerfile",
  "graphql",
  "handlebars",
  "mips",
  "razor",
  "redis",
  "solidity",
];

export const codeLangValues: { [key: string]: string } = {
  auto: "Auto",
  html: "HTML",
  javascript: "JavaScript",
  python: "Python",
  java: "Java",
  c: "C",
  cpp: "C++",
  csharp: "C#",
  php: "PHP",
  css: "CSS",
  scss: "SCSS",
  less: "LESS",
  markdown: "Markdown",
  json: "JSON",
  yaml: "YAML",
  xml: "XML",
  bash: "Bash",
  sql: "SQL",
  go: "Go",
  rust: "Rust",
  dart: "Dart",
  kotlin: "Kotlin",
  swift: "Swift",
  ruby: "Ruby",
  "objective-c": "Objective-C",
  perl: "Perl",
  powershell: "PowerShell",
  r: "R",
  scala: "Scala",
  shellscript: "ShellScript",
  vb: "VB",
  lua: "Lua",
  fsharp: "F#",
  groovy: "Groovy",
  ini: "INI",
  latex: "LaTeX",
  matlab: "MATLAB",
  pascal: "Pascal",
  plaintext: "Plain Text",
  pug: "Pug",
  restructuredtext: "reStructuredText",
  vhdl: "VHDL",
  vue: "Vue",
  coffeescript: "CoffeeScript",
  dockerfile: "Dockerfile",
  graphql: "GraphQL",
  handlebars: "Handlebars",
  mips: "MIPS",
  razor: "Razor",
  redis: "Redis",
  solidity: "Solidity",
  typescript: "TypeScript",
};

let codeLangOptions: any[] = [];
codeLangKeys.forEach((language: string) => {
  codeLangOptions.push({
    value: language,
    label: codeLangValues[language],
  });
});

export default codeLangOptions;
